name = "gras-matchmaker"
main = "src/index.ts"
compatibility_date = "2026-04-09"

# Create a KV namespace and paste its id here:
#   wrangler kv:namespace create GRAS_KV
kv_namespaces = [
  { binding = "GRAS_KV", id = "b49c74e317014373ad5d4e985c407222" }
]

